# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Share an additional folder where the full project is accessible
  config.vm.synced_folder "..", "/jmxtrans_src"

  config.vm.define "centos" do |centos|
    # Every Vagrant virtual environment requires a box to build off of.
    centos.vm.box = "puppetlabs/centos-6.6-64-nocm"

    centos.vm.provision "shell", path: "prerequisites-centos.sh"
    centos.vm.provision "shell", inline: "rpm -i --force /jmxtrans_src/target/rpm/jmxtrans/RPMS/noarch/jmxtrans-*.rpm"
    centos.vm.provision "shell", inline: "/usr/local/bin/bats /jmxtrans_src/vagrant/jmxtrans.bats"
  end

  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "ubuntu/trusty64"
    ubuntu.vm.provider "virtualbox" do |v|
      v.memory = 1024
    end

    ubuntu.vm.provision "shell", path: "prerequisites-ubuntu.sh"
    ubuntu.vm.provision "shell", inline: "DEBIAN_FRONTEND=noninteractive dpkg -i install /jmxtrans_src/target/jmxtrans-*.deb"
    ubuntu.vm.provision "shell", inline: "/usr/local/bin/bats /jmxtrans_src/vagrant/jmxtrans.bats"
  end

end
